### ISSUE TITLE
multicall write all opps at once

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/arb-bot#103]
multicall has a write functionality, ie do multiple write calls at once, this can be pretty usefull for arb bot to submit all opps at once, which will make things much more performant and efficient.

but something to note here is to investigate and examine how to use it and if like multicall read, multicall write has `allowFailure` option for each of the write calls.

for further read:
https://github.com/mds1/multicall#batch-contract-writes

**Comment by dcatki** [comment]
@rouzwelt what's the latest with this? still useful / required / valuable?

**Comment by rouzwelt** [comment]
> @rouzwelt what's the latest with this? still useful / required / valuable?

this is very old i think, it is out of scope  can be closed
