### ISSUE TITLE
🚨 do not log tx that failed to mine on alerts

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/arb-bot#125]
alerts need to be actionable, so tx that fail to mine most likely because of front running should not be included as alerts

**Comment by thedavidmeister** [comment]
@rouzwelt what am i reviewing? i don't see anything

**Comment by rouzwelt** [comment]
> @rouzwelt what am i reviewing? i don't see anything

just wanted you to check it and let me know if the scope is ok and put it on my deck whenever you find it ok

**Comment by rouzwelt** [comment]
the fix is already available in latest stable image called: `flu-module`
