### ISSUE TITLE
🚨 Determine best way to handle subgraph health errors

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#127]
The current alerts for "unhealthy subgraph" are insufficient.

There are multiple things that can lead to this error, so we need to separate those
- indexing errors
- timeouts when pinging the subgraph endpoint
- anything else?

I propose "Unhealthy subgraph" should be reserved for actual indexing errors

Connection issues should be clearer, if there's a persistent timeout, it should say that. BUT, we probably only want to trigger the "subgraph timeout" error if it's persistent over some number of tries.

**Comment by thedavidmeister** [comment]
makes sense to me, if you can't reach the subgraph you can't say whether it is healthy or not, so claiming unhealth is not correct in that case
