### ISSUE TITLE
Quickswap v3 support

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#134]
Yesterday in Telegram it became apparent that the bot is currently unable to find routes or make swaps with Quickswap v3

We will need this supported fairly soon.

**Comment by rouzwelt** [comment]
> Yesterday in Telegram it became apparent that the bot is currently unable to find routes or make swaps with Quickswap v3
> 
> We will need this supported fairly soon.

To get this working we need to investigate or build the following:

algebra that quickswap uses is pretty much the same as univ3, but has different names for pretty much similar methods in univ3, also has a slightly diff salt for calcing pool addresses, the rest are pretty much the same with univ3.
Algebra logic is already implemented for `extractor` which is a newer replacement of `datafetcher`. they are pretty similar, but we are using `datafetcher`, so this makes things easy for us for supporting algebra(quickswapv3) by bringing across the stuff from `extractor` to `datafetcher` with their required changes to be compatible with `datafetcher`.
so things todo in big picture are:

1 - override the address calc logic of base univ3 class to match algebra logic
2 - override the pool data fetching logic in base univ3 class for it to use its compatible abi and method names

I think these are the main steps we need to take to have it covered, ofc small details might come up during implementation, so lets allow some room for that too.

**Comment by rouzwelt** [comment]
todo:
- [x] -  implement changes in sushi repo: https://github.com/rainlanguage/sushiswap/pull/19
- [ ] - update bot with head of sushi once above PR is merged
