### ISSUE TITLE
Bump support for RP4

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#136]
We are trying to arb against PancakeSwap V3, but it appears that the RouteProcessor contract we're using isn't compatible.

It looks like RouteProcessor4 is compatible (pending a passing test by @Siddharth2207), this issue is to track the necessary changes to the bot.

**Comment by rouzwelt** [comment]
necessary changes for bot, are pretty minimal, we just need to point to rp4 route builder fn, instead of rp3.2, thats it all for bot side to be able to run thing on rp4, ofc we need the rp4 contract deployed on the supported chains, most of them have official deployments that are available in sushi lib as literals, but for mising chains, we can just deploy and update the literals on sushi lib for it

**Comment by rouzwelt** [comment]
here is the list of all RP4 deployments:
https://github.com/rainlanguage/sushiswap/blob/60fb2bf0d776ee30ee9f89ab1a22c913513e7023/packages/sushi/src/config/route-processor.ts#L302

in our case missing chains include:
- Flare

**Comment by rouzwelt** [comment]
after this, we would need new Arb contracts deployed with RP4 address of their chain, and used as bot ENVs, so that bot can operate normally

**Comment by rouzwelt** [comment]
todo:

- [x] - update bot to rp4: #135 
- [ ] - deploy RP4 for Flare
- [ ] - deploy RP4 based Arb contracts

**Comment by rouzwelt** [comment]
- [x] - bsc
ob: 0xb1d6D10561D4e1792A7c6B336b0529e4bFb5Ea8F
arb: 0x6EAE39ea6c38207C337b3a083c33d7D5700904bc
rp4: 0x33d91116e0370970444B0281AB117e161fEbFcdD


- [ ] - base
ob: 0x2AeE87D75CD000583DAEC7A28db103B1c0c18b76
arb:
rp4: 0x0389879e0156033202c44bf784ac18fc02edee4f
—
flashborrower:
 ordertaker:
 

- [x] - polygon
ob: 0xc95A5f8eFe14d7a20BD2E5BAFEC4E71f8Ce0B9A6
arb: 0x9B0D254bd858208074De3d2DaF5af11b3D2F377F
rp4: 0x46B3fDF7b5CDe91Ac049936bF0bDb12c5d22202e
—
flashborrower: 0x1dD1d03509d194d2218e04319c62d0ABa0D3E301
 ordertaker: 0xbD8849759749B4d8506bC851aceF0E19F34EaBEE
 

- [ ] - eth
ob: 0xf1224A483ad7F1E9aA46A8CE41229F32d7549A74
arb:
rp4: 0xe43ca1Dee3F0fc1e2df73A0745674545F11A59F5
—
flashborrower: 
ordertaker:
 

- [x] - flare
ob: 0xb06202aA3Fe7d85171fB7aA5f17011d17E63f382
arb: 0x5E5F2Af1e7f8bC1BaF051a6c9F5e22F4C6a69C45
rp4: 0x4Aa9AEf59C7B63CD5C4B2eDE81F65A4225a99d9d
—
flashborrower: 0x29d9cB91abc36bae9f6FC6BF9dB5549Eda2E8933
 ordertaker: 0xe80e7438ce6b1055c8e9CDE1b6336a4F9D53C666 


- [x] - arbitrum
ob: 0x90CAF23eA7E507BB722647B0674e50D8d6468234
arb: 0x7CEf19A4A77E00B189d8527558d5E769aBb1EF14
rp4: 0x544bA588efD839d2692Fc31EA991cD39993c135F 
—
flashborrower: 0x40312EDAB8Fe65091354172ad79e9459f21094E2 
ordertaker: 0x83e866e0CF1a8F7a4CF0605D86197B9966a76693
