### ISSUE TITLE
spike for orders against orders

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/arb-bot#150]
Need to do some investigation on how to properly do an encoded call on arb2() that can end up clearing orders against orders, nowthat there is obv4 with quote(), it can be used to get ratios of orders, so the next step is to figure out the encoding call for arb2().
once that is figured out, we can prepare a implementation plan for #147 and #148 .

expected outcome:
with some simple test show that generic arb contract with encoded call is clearing orders against orders as expected.

refer to #152 for the results

**Comment by hardyjosh** [comment]
This is being continued here: https://github.com/rainlanguage/arb-bot/issues/159

**Comment by hardyjosh** [comment]
All tasks have been completed for this spike, we now know
- we can build and use the Rain CLI binary within our node process
- we can use `clear2` and ensure that there is a minimum bounty payable to cover gas
- we can use the arb contract to clear orders against orders on another orderbook (same chain)
