### ISSUE TITLE
use a cli app directly in bot

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/arb-bot#151]
we need to show that we can execute and use a cli app (for this case, it would be dotrain cli) in bot effectively.

deliverable:
show that dotrain cli app can be executed and used from within the bot, with a simple test

conclusion:
based on the convo we had in tg chat, we already have a similar situation with sushi lib and using it in docker, so this will be pretty much the same, ie, add ob crate as submod, and use nix to build it in docker CI and put the bin in the same docker working dir and execute it as normally with node child process.
This will be prioritized once the ob crate with quoteing capability is ready to use.

**Comment by hardyjosh** [comment]
Is this the same as using the Sushi lib though? I thought that was a node module and here we're taking about using a binary via CLI.
