### ISSUE TITLE
Some simple dashboard/place where I can see all of the Orderbook addresses per network that are being watched by the bots we control

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#190]
This could just be a dash in hyperdx, or whatever is most simple

### Edit:
https://www.hyperdx.io/dashboards/66eca3e839cf7adf418eb04c

the above url redirects to the dashboard where all active bots are listed, showing their chain, order books, subgraphs and name

**Comment by rouzwelt** [comment]
can be built on hyperdx dashboard tables

**Comment by rouzwelt** [comment]
https://www.hyperdx.io/dashboards/66eca3e839cf7adf418eb04c

the above url redirects to the dashboard where all active bots are listed, showing their chain, order books, subgraphs and name

**Comment by hardyjosh** [comment]
This is now complete
