### ISSUE TITLE
Planning issue - wave of bot/alert improvements

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#200]
- [ ] - #82 - 
  - [x] - exec kpi: #206 
      - dashboard on hyperdx with enabled alerts: https://www.hyperdx.io/dashboards/66554220b24d065a796b1d93
  - [ ] - discovery kpi: sidelined for now

- [x] - #198 

- [x] - #199 and https://github.com/rainlanguage/rain.orderbook/pull/881
    owner: rain mnemonic main acc: 0x7177b9d00bb5dbcaaf069cc63190902763783b09

    - base: 0x4cd90ef4fbfc29b896f311f789de0c5cfb073c8ef187c2593ac2b95e4c28d990
    - matchain: 0x11281dfd0f45a7c83d86cfd9caa1c392edcb75e63009f1314f6f1f8ff1931422

- [x] - #202 
    - Dashboards for LOW, MEDIUM and HIGH errors is created on hyperdx dashboard panel, and alerts are activated for each group as follows: 
        - LOW (>= 5 over 30 mins) 
        - MEDIUM (>= 3 over 30 mins)
        - HIGH (>= 1 over 5 mins)
      also normal error alerts that we previously had is still enbaled for now which will alert if any error happens but with a different title, this is done to monitor if the alerts config set for each group is working as we need, and if not we will be able to adjust it accordingly, so we need to know all the errors that happen for now and then manually see that the new alerts we set for each group are alerting effectively, meaning they dont spam or miss reporting etc, this will temporary until we are confident with new setup

- [x] - remove obv3 bots

- [x] - replace all ethers signer/provider actions with viem client: #209 
- [x] - #207 
- [x] - #208 : #212 
- [x] - #213 : effecieny dashboard has been created on hyperdx: https://www.hyperdx.io/dashboards/66eef48472f83c063402ee21

**Comment by rouzwelt** [comment]
#82 is set on hyperdx under block elapsed dashboard

**Comment by dcatki** [comment]
@rouzwelt where is this issue at? is everything done?

**Comment by rouzwelt** [comment]
> @rouzwelt where is this issue at? is everything done?
 yes it is done, all the items are ticked, can review and close if all is ok
