### ISSUE TITLE
Unable to debug error log for hyperdex

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/arb-bot#86]
Unable to debug why the internal error occurs over [here ](https://www.hyperdx.io/search?q=service%3A%22digiocean-base-bot%22+level%3A%22error%22&from=1715592361000&to=1715593261000&tq=May+13+14%3A56%3A01+-+May+13+15%3A11%3A01&lid=3af56fe9-a73b-4ee7-b7a7-43a927382ff5&sk=1715593247377000000&tb=original)

Not able to debug the json span : 
```
"JaegerTag": {
        "details.blockNumber": 14401940,
        "details.marketPrice": "12452.697362352495838444",
        "details.maxInput": "3250000",
        "details.maxInputFixed": "3250000000000000000",
        "details.route": "[\"100.00% ---\\u003e WETH/USDC (UniswapV3 0.01%) \\u003e\\u003e BLOOD/WETH (UniswapV2 0.3%)\"]",
        "error": true,
        "otel.library.name": "arb-bot-tracer",
        "otel.status_code": "ERROR",
        "span.kind": "internal"
    }
```

**Comment by rouzwelt** [comment]
hops calldata are only logged on the last hop, for the res of hops the calldata can be calculated by simply decoding the last hop's calldata, exchanging the maxinput and encoding it again
