### ISSUE TITLE
setup alarm for the bot

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/arb-bot#90]
setting alarm for bot is resolved through webhook to the telegram channel https://t.me/RainArbBotStatus

~need to merge https://github.com/rainlanguage/arb-bot/pull/83 so the alerts can be set in hyperdx and then they will be sent to telegram on specified triggers~

This is now dependent on:

- [x] #82 (code side is done, #89 )
- [x] #91 
- [x] #95 (#96 ) (rolled out only on baku and digiocean flare bot atm, WIP)

**Comment by rouzwelt** [comment]
the alerst are up for `baku` and `digiocean` flare bots
